### ISSUE TITLE
Parsing fails when boundary ends with `--`

### ISSUE THREAD

**Issue by mauricelam** [MQpeng/eml-parse-js#54]
I am trying to parse a Blink generated MHTML file (via Save As > Webpage, Single File), but it is not able to show any contents.

After running through the code with a debugger, I think the reason is that the boundary `----MultipartBoundary--GsIBda0vjy2AKIAIliwl7JMwezXDRjDAsLje9khd5l----` ends with `--`.

This confuses the `/\-\-(\r?\n)?$/g.test(line)` check in https://github.com/MQpeng/eml-parse-js/blob/dbed46df87bc7b8e5fc139200baac33a28470807/src/index.ts#L356 and makes it skip over the whole part.

(Wikipedia also has an example of such a MHTML file: https://en.wikipedia.org/wiki/MHTML)

**Comment by MQpeng** [comment]
Thanks for reporting the issue. Due to my current work commitments, I'm unable to address it right now.If you're interested and have the expertise to contribute, we would greatly appreciate your help in resolving this issue.
