### ISSUE TITLE
Types not exposed in package

### ISSUE THREAD

**Issue by wwsalmon** [MQpeng/eml-parse-js#57]
I would like to reference `EmailAddress`, `Attachment`, and `BoundaryHeaders` types in my project, but they do not appear to be exported.

It seems all it would take to change that would be to add these interfaces in the exports in `index.ts`.

Would you consider making this change so that these types can be imported in a project that uses `eml-parse-js`?

**Comment by jasperverbeet** [comment]
I need this too :)! Any chance you could deploy a new version?

I'm now doing stuff like this, which isn't the most elegant.

```ts
type EmlJson = NonNullable<
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  Parameters<Extract<Parameters<typeof readEml>[1], (...args: any) => any>>[1]
>;
```

**Comment by MQpeng** [comment]
release:[1.2.0-beta.0](https://www.npmjs.com/package/eml-parse-js/v/1.2.0-beta.0)

**Comment by wwsalmon** [comment]
thank you for adding :)
